# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d686e23b2cef7c7a7a14ef693332fa777fd25f19452ac6e01bae7ed04fe21f6717ad30871f0d752048bd9b645cafefd6ab5863628ae49e68f58c77eae0959d61

test:
  secret_key_base: 4b6114fd137ed2903142fb970feab5a53c99f10ef3dd4235b66470946a307a4236490762af94f58d309ac0edfb305ec22ae633a239ca503139a10d47288c6c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
